<html>
    <title>FORMULÁRIO DE LOGIN</title>

    <style>
        body{
            background-image: linear-gradient(45deg, rgb(0, 0, 0), rgb(204, 7, 7));
            text-align: center;
            font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
        }

        .form:hover{
            margin: 170px;
            background-color: black;
            display: inline-block;
            padding: 15px;
            transition: 1s;
            width: 270px;
            opacity: 100%;
            border: 2px solid white;
            border-radius: 25px;
        }

        button{
            padding: 5px;
            border:  1px solid red;

        }

        .form{
            margin: 170px;
            background-color: black;
            display: inline-block;
            padding: 15px;
            width: 270px;
            opacity: 30%;
            border: 2px solid white;
            border-radius: 25px;
        }

        h3{
            color: white;
        }

        input{
            padding: 3px;
            border: 2px solid rgb(255, 255, 255);
            text-align: center;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
        }

        label{
            color: white;
        }

    </style>

    <body>
        <div class="form">
            <h3>FORMULÁRIO DE LOGIN</h3>
            <p>
                <label for="email">E-mail</label>
                <input type="text" placeholder="Ex: seu0email@gmail.com">
                <p>
                    <label for="password">Senha</label>
                    <input type="password" placeholder="Ex: A2*3d.!dW#">
                </p>
                <p>
                   
                    <form onsubmit="debug(event)">
                        <button type="submit">ENTRAR</button>
                    </form>

                    
                </p>
            </p>
        </div>
    </body>

</html>
